apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  ports:
  - name: {{ .Values.appName }}-service-port
    protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
  - name: {{ .Values.appName }}-actuator-port
    protocol: TCP
    port: {{ .Values.actuatorServicePort }}
    targetPort: {{ .Values.actuatorContainerPort }}