apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{ .Values.containerPort }}
  # - name: actuator
  #   protocol: TCP
  #   port: {{ .Values.actuatorServicePort }}
  #   targetPort: {{ .Values.actuatorContainerPort }}